pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker { image 'node:14-buster' }
            }
            environment {
                VITE_API_URL = 'https://graph.zubr.app/api/rest'
                VITE_BOT_URL = '/'
            }
            steps {
                sh 'yarn'
                sh 'yarn run build-all'
                sh 'rm -rf dist'
                sh 'mv packages/main/dist dist/'
                sh 'mv packages/ik/dist dist/ik/'
                sh 'ls -l'
                stash includes: 'dist/',
                      name: 'dist',
                      useDefaultExcludes: true
            }
        }
        stage('Deploy') {
            environment {
                DIGITALOCEAN_ACCESS_TOKEN = credentials('DIGITALOCEAN_ACCESS_TOKEN')
                def HOSTS = sh(
                    script: "doctl compute droplet list --format PublicIPv4 --no-header --tag-name zubr_in| tr '\n' ','",
                    returnStdout: true
                ).trim()
            }
            steps {
                unstash 'dist'
                ansiblePlaybook(
                      playbook: 'infrastructure/deploy.yml',
                      inventory: "$HOSTS,",
                      credentialsId: "CURRENT_DEPLOY_KEY",
                      hostKeyChecking: false
                )
            }
        }
    }
    post {
        always {
            notifyBuild(currentBuild.result)
        }
    }
}

def notifyBuild(def buildStatus) {
    // set default of build status
    buildStatus =  buildStatus ?: 'SUCCESS'
    GIT_COMMIT_MSG = sh (
        script: "git log --format=format:%s -1 ${GIT_COMMIT}",
        returnStdout: true
    ).trim()
    def emojiMap = [ 'STARTED': '#F0FFFF', 'SUCCESS': '✅', 'FAILURE': '🛑' ]
    telegramSend """
${emojiMap[buildStatus]} *${JOB_NAME}* - ${buildStatus}
${env.RUN_DISPLAY_URL}
${GIT_COMMIT_MSG}
"""
}

